language: node_js
node_js:
  - '4'
  - '6'
script:
  - npm run lint
  - npm test
env:
  global:
    secure: QherUXuEW/O3ypBmB3+AHSXg+wCCGFndFtGi29IYH1A3rjLP1NP37h7+pcFSFuhyOC8jDv+XzcwK+1hQGcsMjNAP0LQnLuU/0TbGufeyQMyz1/phGjvrwGs7fXN6vmj6GzcVZvjPB0+p0H2no9LhgZsdZsdOO67pC1DOMyhI1C23SDuSlenl2HD0ZWhD7BpsbrPrN0bYhi64nEBv7pAqtkduc+EyDhDwbHq+xSRbkWqqJUzDD5jRkXKZHlyTSripkMgD05D/Egd5poRAdRLFClgGZXr/dqvJjSSTaUSl38VLk87WkeK0cZaGh0nbh8F89wcBbQss/pklVuevprPFwniCIpFaJDo+QfJeyeUL40665fLKNmwZwe2oqZTFhMOOuN+NTRANKA0r1kraZ3DVA3eVQYodFRwNbWFZnkZcRN7hf0+vlzy3uXcxvEmyaLrWD9RHwfBs+2qM9olqT5+aA4zrKsf0Iegh5gFuSnjS6e13jznwHi9M1tbw52WOKNe/s+LIs0muqGvuWy+ge2Of11CCR82GXleavG12LOu2+adyGhSxXt9zzOde8hoKk+EJGs8mfVZZsboLYPylNwtAFFGKElr6DQweGrqhDmcIZNQ9UjeowgmytqjjNdnGPiTSxm1H5Gytrf8qF9k8vx8gW8wVee6/noxZjw44jOvehTA=
deploy:
  provider: npm
  email: mahnunchik@gmail.com
  api_key:
    secure: YnieJVD0BtDyFT5ni/2ll+aaatqugUwhauvpamwLJNRJXgUG3Ud/SdeUKHqyx8bL/Wu3HP0TuSulewBMTj1y5ZdUrQ63SvdfbaczH2WXqTB4SgXAMn+HKPIgwr2+VyqI28aYaOqQ6oB3rSG0Uisz0OOOIaECMsjo6AAnKmU9fYkzJx9eII8aQW3dBYq5ioYM8kc8FqHXmJkFYnPbp/uC1G10Uy7M9WARvpV01geVH1W0W13mRtdPqG8zFvDKZb98uYd99mJ80/JNsrBUHEoyiggmdHaTUD0KXw75st6XpYNp40VgMN6QNoxSU/VpY+mp7Q2i6PtQPifVGiL9liLHFIH0Ubr0bntk3QuPhw8pPIV3nVs4ogq2yC+2nIM5El3Ta5bIzffqqX12RPWrOxyFSqEYmSsbddkqeybUKIq9q2tRritXm9KoVJoSx6SATxMKMLMJySqQ4cHjwBENg0wa10NZUQPHK0FKGEDPBKZuiLDUlnPpTd3T4k4cmUanznypM2S9NfAbP0bE9LiKDqkcpueH/u2aLv7AfUroWdzBaI9gBKaWe7wlA1TxY2dCP9o5o5ZmMXrBqHvf+YHSRVKz14rajpPT1a55tk0HoezpJiZdGP9HBPCdYQVy9VuvZhcWJS9zRQ/ewNePi1mhwM0Gub1hfijx87yZN9HCUpAoQXw=
  on:
    tags: true
    repo: mahnunchik/telegram-promise
    node: '6'
