language: node_js
node_js:
  - '4'
  - '5'
script:
  - npm run lint
  - npm test
env:
  global:
    secure: QherUXuEW/O3ypBmB3+AHSXg+wCCGFndFtGi29IYH1A3rjLP1NP37h7+pcFSFuhyOC8jDv+XzcwK+1hQGcsMjNAP0LQnLuU/0TbGufeyQMyz1/phGjvrwGs7fXN6vmj6GzcVZvjPB0+p0H2no9LhgZsdZsdOO67pC1DOMyhI1C23SDuSlenl2HD0ZWhD7BpsbrPrN0bYhi64nEBv7pAqtkduc+EyDhDwbHq+xSRbkWqqJUzDD5jRkXKZHlyTSripkMgD05D/Egd5poRAdRLFClgGZXr/dqvJjSSTaUSl38VLk87WkeK0cZaGh0nbh8F89wcBbQss/pklVuevprPFwniCIpFaJDo+QfJeyeUL40665fLKNmwZwe2oqZTFhMOOuN+NTRANKA0r1kraZ3DVA3eVQYodFRwNbWFZnkZcRN7hf0+vlzy3uXcxvEmyaLrWD9RHwfBs+2qM9olqT5+aA4zrKsf0Iegh5gFuSnjS6e13jznwHi9M1tbw52WOKNe/s+LIs0muqGvuWy+ge2Of11CCR82GXleavG12LOu2+adyGhSxXt9zzOde8hoKk+EJGs8mfVZZsboLYPylNwtAFFGKElr6DQweGrqhDmcIZNQ9UjeowgmytqjjNdnGPiTSxm1H5Gytrf8qF9k8vx8gW8wVee6/noxZjw44jOvehTA=
